-- appearance.lua -- Visual and rendering settings for agentic work.

local wezterm = require("wezterm")
local utils = require("utils")

local M = {}

function M.apply(config)
  -- Front-end rendering: WebGPU with a 30 FPS cap for smooth but efficient output.
  config.front_end = "WebGpu"
  config.max_fps = 30
  config.animation_fps = 30

  -- Prefer a discrete GPU when available; on battery fall back to the iGPU to
  -- save power and VRAM. name/backend/device_type are part of WezTerm's GpuInfo.
  local battery = utils.battery_status()
  if not (battery and battery.status == "Discharging") then
    config.webgpu_preferred_adapter = {
      name = "",
      backend = "Vulkan",
      device_type = "DiscreteGpu",
    }
  end

  -- Scrollback for long agent logs and build output (was 100000; trimmed for RAM).
  config.scrollback_lines = 25000
  config.enable_scroll_bar = true

  -- Host profile tunables (generated by dotfiles/scripts/host-profile.sh) override
  -- the hardcoded scrollback/FPS above when present; pcall keeps a missing or
  -- broken file from breaking startup. Battery/focus handlers below still cap at 30.
  do
    local ok, tunables = pcall(dofile, os.getenv("HOME") .. "/.local/state/wezterm/tunables.lua")
    if ok and type(tunables) == "table" then
      if type(tunables.scrollback_lines) == "number" then
        config.scrollback_lines = tunables.scrollback_lines
      end
      if type(tunables.max_fps) == "number" then
        config.max_fps = tunables.max_fps
      end
      if type(tunables.animation_fps) == "number" then
        config.animation_fps = tunables.animation_fps
      end
    end
  end

  -- Color scheme and font.
  -- Use the system "JetBrains Mono" family; WezTerm's built-in Nerd Font symbols
  -- (Symbols Nerd Font Mono) are automatically added as a fallback for glyphs.
  config.color_scheme = "Catppuccin Mocha"
  config.font = wezterm.font("JetBrains Mono", { weight = "Medium" })
  config.font_size = 12.0
  config.line_height = 1.2

  -- Font rendering tweaks for crisp text at small sizes.
  config.freetype_load_target = "Light"
  config.freetype_render_target = "HorizontalLcd"

  -- Window / tab appearance.
  config.window_decorations = "RESIZE"
  config.window_padding = { left = 4, right = 4, top = 4, bottom = 4 }
  config.use_fancy_tab_bar = true
  config.tab_bar_at_bottom = true
  config.hide_tab_bar_if_only_one_tab = false
  config.show_new_tab_button_in_tab_bar = true

  -- Inactive pane dimming makes it obvious which pane is receiving input.
  config.inactive_pane_hsb = {
    saturation = 0.85,
    brightness = 0.65,
  }


  -- Visual bell config (audible bell is disabled in status.lua).
  config.visual_bell = {
    fade_in_function = "EaseIn",
    fade_in_duration_ms = 75,
    fade_out_function = "EaseOut",
    fade_out_duration_ms = 75,
  }

  -- FPS is capped at 30 everywhere; keep the focus handlers only so low-battery
  -- overrides can be added later without touching the baseline.
  wezterm.on("window-focus-lost", function(window, pane)
    window:set_config_overrides({ max_fps = 30 })
  end)

  wezterm.on("window-focus-gained", function(window, pane)
    window:set_config_overrides({ max_fps = 30 })
  end)
end

return M
