#!/usr/bin/env bash
# =============================================================================
# agent-maintenance.sh — daily cleanup for agent logs and registry records.
#
# - Prunes ~/.cache/agent-logs/*.log: deletes files older than
#   AGENT_LOG_MAX_AGE_DAYS (default 7), then caps the directory at
#   AGENT_LOG_CAP files (default 200) — both from the host profile
#   (~/.local/state/host/profile.env) when present.
# - Prunes stale agent registry records in ~/.local/state/agents/registry/*.json:
#   deletes records whose state is "exited" and whose updated_at is older than
#   7 days. Requires jq; skips with a warning otherwise.
#
# Usage: agent-maintenance.sh [--dry-run]
# =============================================================================

set -euo pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# ---- host profile (adaptive retention) --------------------------------------
# Generated by dotfiles/scripts/host-profile.sh; plain KEY=VALUE assignments,
# safe to source under `set -u`. Missing file/keys fall back to defaults below.
if [[ -r "$HOME/.local/state/host/profile.env" ]]; then
  # shellcheck disable=SC1091
  source "$HOME/.local/state/host/profile.env"
fi

LOG_DIR="${AGENT_LOG_DIR:-$HOME/.cache/agent-logs}"
REGISTRY_DIR="${AGENT_REGISTRY_DIR:-$HOME/.local/state/agents/registry}"
LOG_MAX_AGE_DAYS="${AGENT_LOG_MAX_AGE_DAYS:-7}"
LOG_MAX_FILES="${AGENT_LOG_CAP:-200}"
REGISTRY_MAX_AGE_DAYS=7

removed_logs_age=0
removed_logs_cap=0
removed_records=0

# ------------------------------------------------------------------------------
# Agent logs: age-based prune
# ------------------------------------------------------------------------------
if [[ -d "$LOG_DIR" ]]; then
  while IFS= read -r -d '' f; do
    if $DRY_RUN; then
      echo "[dry-run] would delete old log: $f"
    else
      rm -f "$f"
    fi
    removed_logs_age=$((removed_logs_age + 1))
  done < <(find "$LOG_DIR" -maxdepth 1 -type f -name '*.log' -mtime +"$LOG_MAX_AGE_DAYS" -print0 2>/dev/null)

  # Cap at LOG_MAX_FILES files (oldest first beyond the cap).
  while IFS= read -r f; do
    if $DRY_RUN; then
      echo "[dry-run] would delete log over cap: $f"
    else
      rm -f "$f"
    fi
    removed_logs_cap=$((removed_logs_cap + 1))
  done < <(find "$LOG_DIR" -maxdepth 1 -type f -name '*.log' -printf '%T@ %p\0' 2>/dev/null \
    | sort -zn \
    | awk -v RS='\0' -v keep="$LOG_MAX_FILES" 'NR > keep { sub(/^[0-9.]+ /, ""); print }')

  remaining_logs=$(find "$LOG_DIR" -maxdepth 1 -type f -name '*.log' 2>/dev/null | wc -l)
else
  remaining_logs=0
fi

# ------------------------------------------------------------------------------
# Registry: prune exited records older than REGISTRY_MAX_AGE_DAYS
# ------------------------------------------------------------------------------
if [[ -d "$REGISTRY_DIR" ]]; then
  if command -v jq >/dev/null 2>&1; then
    cutoff_epoch=$(date -d "$REGISTRY_MAX_AGE_DAYS days ago" +%s)
    for f in "$REGISTRY_DIR"/*.json; do
      [[ -f "$f" ]] || continue
      state="$(jq -r '.state // empty' "$f" 2>/dev/null || true)"
      updated_at="$(jq -r '.updated_at // empty' "$f" 2>/dev/null || true)"
      [[ "$state" == "exited" ]] || continue
      [[ -n "$updated_at" ]] || continue
      updated_epoch=$(date -d "$updated_at" +%s 2>/dev/null || echo 0)
      if [[ "$updated_epoch" -lt "$cutoff_epoch" ]]; then
        if $DRY_RUN; then
          echo "[dry-run] would delete stale record: $f (exited, updated_at=$updated_at)"
        else
          rm -f "$f"
        fi
        removed_records=$((removed_records + 1))
      fi
    done
  else
    echo "WARNING: jq not found; skipping registry prune" >&2
  fi
fi

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------
echo "agent-maintenance: logs aged-out=$removed_logs_age, logs over-cap=$removed_logs_cap, remaining=$remaining_logs, stale registry records=$removed_records$($DRY_RUN && echo ' (dry run)')"
