#!/usr/bin/env bash
# =============================================================================
# agent-health-metrics.sh — append one snapshot of agent-host health metrics.
#
# Appends ONE pipe-delimited line to ~/.local/state/agents/metrics.log:
#   timestamp | loadavg | tmux RSS (KB) | nvim RSS (KB) | wezterm RSS (KB)
#   | tmux sessions | tmux panes | agent-logs size | registry records
#   | host effective tier (from host-profile.sh, "unknown" if unavailable)
#
# Every command is guarded so the script works even when tmux/wezterm/nvim
# are not running.
#
# Usage: agent-health-metrics.sh
# =============================================================================

set -euo pipefail

# ---- host profile (effective tier label) ------------------------------------
# Generated by dotfiles/scripts/host-profile.sh; plain KEY=VALUE assignments,
# safe to source under `set -u`. Missing file/keys fall back to defaults below.
if [[ -r "$HOME/.local/state/host/profile.env" ]]; then
  # shellcheck disable=SC1091
  source "$HOME/.local/state/host/profile.env"
fi

LOG_DIR="${AGENT_LOG_DIR:-$HOME/.cache/agent-logs}"
REGISTRY_DIR="${AGENT_REGISTRY_DIR:-$HOME/.local/state/agents/registry}"
METRICS_DIR="${AGENT_METRICS_DIR:-$HOME/.local/state/agents}"
METRICS_LOG="$METRICS_DIR/metrics.log"

mkdir -p "$METRICS_DIR"

ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
loadavg="$(cut -d' ' -f1 /proc/loadavg 2>/dev/null || echo 0)"

rss_for() { # $1 = process-name prefix (comm may contain spaces, e.g. "tmux: server")
  ps -eo rss=,comm= 2>/dev/null \
    | awk -v p="$1" '{ name=$2; for (i=3; i<=NF; i++) name=name " " $i; if (name ~ ("^" p)) s += $1 } END { print s + 0 }'
}

tmux_rss="$(rss_for tmux)"
nvim_rss="$(rss_for nvim)"
wezterm_rss="$(rss_for wezterm)"

tmux_sessions=0
tmux_panes=0
if command -v tmux >/dev/null 2>&1 && tmux list-sessions >/dev/null 2>&1; then
  tmux_sessions="$(tmux list-sessions 2>/dev/null | wc -l)"
  tmux_panes="$(tmux list-panes -a 2>/dev/null | wc -l)"
fi

if [[ -d "$LOG_DIR" ]]; then
  logs_size="$(du -sh "$LOG_DIR" 2>/dev/null | cut -f1)"
else
  logs_size=0
fi

registry_count=0
if [[ -d "$REGISTRY_DIR" ]]; then
  registry_count="$(find "$REGISTRY_DIR" -maxdepth 1 -type f -name '*.json' 2>/dev/null | wc -l)"
fi

printf '%s | load=%s | tmux_rss_kb=%s | nvim_rss_kb=%s | wezterm_rss_kb=%s | tmux_sessions=%s | tmux_panes=%s | agent_logs_size=%s | registry_records=%s | tier=%s\n' \
  "$ts" "$loadavg" "$tmux_rss" "$nvim_rss" "$wezterm_rss" "$tmux_sessions" "$tmux_panes" "$logs_size" "$registry_count" "${HOST_EFFECTIVE_TIER:-unknown}" \
  >> "$METRICS_LOG"

echo "metrics appended to $METRICS_LOG"
